version: 2.1 # Use 2.1 to enable using orbs and other features.

orbs:
  ruby: circleci/ruby@1.2.0
  node: circleci/node@2

commands:
  rspec:
    parameters:
      out-path:
        default: /tmp/test-results/rspec
        description: >-
          Where to save the rspec.xml file. Will automatically be saved to
          test_results and artifacts on CircleCI.
        type: string
    steps:
      - run:
          command: >
            mkdir -p <<parameters.out-path>>

            bundle exec rspec --format RspecJunitFormatter --out <<parameters.out-path>>/results.xml --format progress
          name: "Run tests with RSpec"
      - store_test_results:
          path: <<parameters.out-path>>
      - store_artifacts:
          destination: test-results
          path: <<parameters.out-path>>
  # Have to override the command from the ruby orb, since it doesn't support the --add-platform command
  # Since this command wholly comes from the ruby orb, the best documentation can be found at: https://circleci.com/developer/orbs/orb/circleci/ruby
  install-deps:
    description: Install gems with Bundler.
    parameters:
      app-dir:
        default: .
        description: >
          Path to the directory containing your Gemfile file. Not needed if Gemfile
          lives in the root.
        type: string
      bundler-version:
        default: ""
        description: >
          Configure which version of bundler to install and utilize. By default, it
          gets the bundler version from Gemfile.lock, but if it is not working use
          this to override.
        type: string
      key:
        default: gems-v1
        description: The cache key to use. The key is immutable.
        type: string
      path:
        default: ./vendor/bundle
        description: >
          Installation path. By default, it will run bundle with `--deployment` flag
          and installs gems to the vendor/bundle directory.
        type: string
      with-cache:
        default: true
        description: Enable automatic caching of your gemfile dependencies for increased speed.
        type: boolean
      platform:
        default: "x86_64-linux"
        type: string
    steps:
      - when:
          condition: <<parameters.with-cache>>
          steps:
            - restore_cache:
                keys:
                  - >-
                    << parameters.key >>-{{ checksum
                    "<<parameters.app-dir>>/Gemfile"  }}-{{ .Branch }}
                  - >-
                    << parameters.key >>-{{ checksum
                    "<<parameters.app-dir>>/Gemfile"  }}
                  - << parameters.key >>
      - run:
          command: |

            # we use an pinned bundler version for jruby
            if [ "<< parameters.key >>" == "circleci/jruby:9.2.11.0-node" ]; then
              gem install bundler -v 2.3.26
            else
              gem install bundler
            fi

            # where we add the platform command to allow CircleCI to bundle
            bundle lock --add-platform <<parameters.platform>> 
            if [ "<< parameters.path >>" == "./vendor/bundle" ]; then
              bundle config set deployment 'true'
            fi
            bundle config set path << parameters.path >>
            bundle check || bundle install
          name: >-
            Bundle Install <<^parameters.with-cache>>(No
            Cache)<</parameters.with-cache>>
          working_directory: <<parameters.app-dir>>
      - when:
          condition: <<parameters.with-cache>>
          steps:
            - save_cache:
                key: >-
                  << parameters.key >>-{{ checksum
                  "<<parameters.app-dir>>/Gemfile"  }}-{{ .Branch }}
                paths:
                  - <<parameters.app-dir>>/<< parameters.path >>

jobs:
  test:
    parameters:
      version:
        default: "cimg/ruby:3.0-node"
        description: Ruby image to use
        type: string
    docker:
      - image: <<parameters.version>>
    steps:
      - checkout
      - install-deps:
          key: <<parameters.version>>
      - rspec

workflows:
  version: 2
  test:
    jobs:
      - test:
          matrix:
            parameters:
              version:
                - "cimg/ruby:3.0-node"
                - "cimg/ruby:2.7-node"
                - "cimg/ruby:3.1-node"
                - "circleci/jruby:9.2.11.0-node"
